services:
  - type: web
    name: Weather-app
    env: python
    plan: free
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
      python manage.py migrate
    startCommand: cd Weather && gunicorn Weather.wsgi:application --bind 0.0.0.0:$PORT --timeout 120 --workers 3
    envVars:
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
